# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8c5793f4b7e4f418e49ba7917fb0deceb40215ba8e7ef44662c49aa3f8e295289e68ec6cb4cffeef867326bbd24db61c379884dc64f0947f15d2bb57acb5b21

test:
  secret_key_base: 0971994d0be95ebe0f9d5ce2e5724e1693593f701a91c416d83ce8c3a0c7b4b8c256a13df03a7c81d1ec2a7d59b6cc3e5b50b2b98cb5aac31c4b9af6800a6e31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
